server:
  port: 8888
spring:
  application:
    name: chapter6-configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/

